### ISSUE TITLE
Unavailable on multi-screen situation

### ISSUE THREAD

**Issue by greyovo** [mdhiggins/CenterTaskbar#16] opened 2020-09-03 04:06 UTC
It doesnt work in the 2nd screen while the main screen is working great.

**Comment by greyovo** [comment] 2020-09-03 04:09
Using Windows 10 1909 18363.1016. Does the version thing lead to this problem?

**Comment by mdhiggins** [comment] 2020-09-03 09:15
Should work fine on multi monitor setups. I use 2 monitors without issue daily. What's not working can you post screenshots and be more specific

**Comment by greyovo** [comment] 2020-09-03 09:23
@mdhiggins 
![Snipaste_2020-09-03_17-21-29](https://user-images.githubusercontent.com/20888390/92096826-eefe9700-ee09-11ea-90dc-307cf0c4d4b9.jpg)

It works in my laptop's screen (the right one) and doesn't with my AOC monitor(the left one)

**Comment by mdhiggins** [comment] 2020-09-04 16:52
https://github.com/mdhiggins/CenterTaskbar/releases/tag/1.3

Try that

**Comment by greyovo** [comment] 2020-09-04 16:55
@mdhiggins 
Tried and didn't fix.

**Comment by mdhiggins** [comment] 2020-09-04 16:57
Does removing that toolbar addon you have fix things? the one with your upload and download speeds

**Comment by greyovo** [comment] 2020-09-04 16:59
@mdhiggins Wow amazing! I removed that addon and it works. Seems that is the reason.
Thanks bro :)

**Comment by mdhiggins** [comment] 2020-09-04 17:01
That latest update should have addressed extra toolbars breaking things though. What toolbar is that? 

Can you make sure you have the 1.3 binary running? I just uploaded it like a few minutes ago

**Comment by greyovo** [comment] 2020-09-04 17:06
The toolbar I use: https://github.com/zhongyang219/TrafficMonitor

Yes I have downloaded the latest version as soon as I received your reply several minutes ago.

**Comment by mdhiggins** [comment] 2020-09-04 17:07
I'll grab that and see if I can reproduce this issue

**Comment by greyovo** [comment] 2020-09-04 17:08
Thanks for your job.

**Comment by mdhiggins** [comment] 2020-09-04 17:10
Hm works for me on the new and old builds, not sure why its bugging out for you. Does look like that program is injecting into the toolbar using some unofficial means so maybe just some weirdness.

If you wanted to run from source for debug logs I'll take a look or you can just close this

**Comment by greyovo** [comment] 2020-09-04 17:19
I may build it from souce but I was not so familiar with .NET project.  I'll try it. And if I cant do this i will close this issue.

**Closed as completed** 2020-09-08 17:58 UTC
