### ISSUE TITLE
Not refreshing on unplug/plug external monitor. Scan for screen is not triggered when monitor plug/unplug

### ISSUE THREAD

**Issue by rodrigolopezguerra** [mdhiggins/CenterTaskbar#18] opened 2020-10-05 13:27 UTC
**Describe the bug**
I have an external monitor conected to a HUB that connects to my pc thougth USB C. When unplug/plug the monitor , the icons are moved and dont refresh con new screen. Need to refresh manually

**To Reproduce**
1 . Unplug/or switch off monitor
2 . Desktop moves to laptor screen
3. Icons are not centered anymore (They are moved to the left/rigth, seems like position is not being recalculated since it's not the standar position either)
4. I look up for the app , and select the "Scan for screen"
5. Get fixed

**Expected behavior**
Scan for screen is triggered automatically when plug/unplug monitor

**Screenshots**

A . Taskbar on notebook desktop after unplug monitor

![image](https://user-images.githubusercontent.com/3514141/95085134-31f7a700-06f5-11eb-9d29-a676c28de722.png)

B . Selecting "Scan for screen"
![image](https://user-images.githubusercontent.com/3514141/95085181-3e7bff80-06f5-11eb-9ba7-3b4045c94a82.png)

C. OK taskbar 

![image](https://user-images.githubusercontent.com/3514141/95085219-476cd100-06f5-11eb-9df9-6a8bebe4d6eb.png)

**Additional context**
Thanks for the great up , really enjoying !

**Comment by mdhiggins** [comment] 2020-10-05 15:04
Duplicate of #17

**Comment by mdhiggins** [comment] 2020-10-05 15:06
Technically its a feature request not a bug but a7163e8f6447d11ed8d6a210f1b593751a1d1100 should add this feature

**Comment by rodrigolopezguerra** [comment] 2020-10-05 15:08
A really thin line in this scenario  haha. 
Nevertheless i can't do anything else that thanking you for your work that i enjoy using everyday !

**Comment by mdhiggins** [comment] 2020-10-05 15:16
Let me know if that works and I'll close this out and publish a new release build

**Comment by mdhiggins** [comment] 2020-10-07 13:23
What's the word?

**Closed as completed** 2020-10-08 00:30 UTC

**Comment by rodrigolopezguerra** [comment] 2020-10-08 21:50
couldn't test it. Is there a compiled version? I'll installed right now


*Rodrigo López Guerra       *
Whatsapp*: 1568383333
<https://api.whatsapp.com/send?phone=541168383333&text=Hola!%20Como%20estas?%20Genial%20estar%20en%20contacto>*

**Comment by mdhiggins** [comment] 2020-10-09 00:03
Yes check releases

**Comment by rodrigolopezguerra** [comment] 2020-10-09 17:40
Hi , just try it out. When i unplug the monitor , it works on my laptop.
When i plug the monitor again did not work.

Let me know if y can try something else to help


*Rodrigo López Guerra       *
Whatsapp*: 1568383333
<https://api.whatsapp.com/send?phone=541168383333&text=Hola!%20Como%20estas?%20Genial%20estar%20en%20contacto>*

**Comment by rodrigolopezguerra** [comment] 2020-10-09 17:41
Also i got this error after scanning manually

[image: image.png]


*Rodrigo López Guerra       *
Whatsapp*: 1568383333
<https://api.whatsapp.com/send?phone=541168383333&text=Hola!%20Como%20estas?%20Genial%20estar%20en%20contacto>*

**Comment by mdhiggins** [comment] 2020-10-09 18:05
Image not attached

**Comment by rodrigolopezguerra** [comment] 2020-10-09 18:56
![image](https://user-images.githubusercontent.com/3514141/95621352-ea9c4e00-0a47-11eb-8c11-967f18155483.png)

**Comment by mdhiggins** [comment] 2020-10-09 20:15
Not able to reproduce this, works fine on my end include monitor changes

Does the details button provide any information? Otherwise I would need you to run it from source and see what the error is

**Comment by rodrigolopezguerra** [comment] 2020-10-09 21:11
couldn't reproduce it again. Will report when happens again

strange.

Thanks !


*Rodrigo López Guerra       *
Whatsapp*: 1568383333
<https://api.whatsapp.com/send?phone=541168383333&text=Hola!%20Como%20estas?%20Genial%20estar%20en%20contacto>*

**Comment by rodrigolopezguerra** [comment] 2020-10-10 15:24
@mdhiggins Today the error came back

![image](https://user-images.githubusercontent.com/3514141/95658796-75865280-0af3-11eb-9c5a-309b40cce02d.png)

Here's the detailed information :

See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

```
************** Exception Text **************
System.AggregateException: One or more errors occurred. ---> System.AggregateException: One or more errors occurred. ---> System.Threading.Tasks.TaskCanceledException: A task was canceled.
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at CenterTaskbar.TrayApplication.<>c.<CancelPositionThread>b__28_0(Task theTask)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object <p0>)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Parallel.ForWorker[TLocal](Int32 fromInclusive, Int32 toExclusive, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Func`4 bodyWithLocal, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEachWorker[TSource,TLocal](IEnumerable`1 source, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEach[TSource](IEnumerable`1 source, Action`1 body)
   at CenterTaskbar.TrayApplication.CancelPositionThread()
   at CenterTaskbar.TrayApplication.Restart(Object sender, EventArgs e)
   at System.Windows.Forms.MenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.MenuItem.MenuItemData.Execute()
   at System.Windows.Forms.Command.Invoke()
   at System.Windows.Forms.NotifyIcon.WndProc(Message& msg)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
---> (Inner Exception #0) System.AggregateException: One or more errors occurred. ---> System.Threading.Tasks.TaskCanceledException: A task was canceled.
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at CenterTaskbar.TrayApplication.<>c.<CancelPositionThread>b__28_0(Task theTask)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object <p0>)
---> (Inner Exception #0) System.Threading.Tasks.TaskCanceledException: A task was canceled.<---
<---



************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4220.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
----------------------------------------
CenterTaskbar
    Assembly Version: 1.1.7583.19874
    Win32 Version: 1.1.7583.19874
    CodeBase: file:///C:/Users/rodrigo/Downloads/CenterTaskbar%20(1).exe
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4200.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4200.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3752.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
UIAutomationClient
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4220.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/UIAutomationClient/v4.0_4.0.0.0__31bf3856ad364e35/UIAutomationClient.dll
----------------------------------------
UIAutomationTypes
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4220.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/UIAutomationTypes/v4.0_4.0.0.0__31bf3856ad364e35/UIAutomationTypes.dll
----------------------------------------
UIAutomationProvider
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4220.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/UIAutomationProvider/v4.0_4.0.0.0__31bf3856ad364e35/UIAutomationProvider.dll
----------------------------------------
WindowsBase
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4220.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/WindowsBase/v4.0_4.0.0.0__31bf3856ad364e35/WindowsBase.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4220.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
UIAutomationClientsideProviders
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4220.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/UIAutomationClientsideProviders/v4.0_4.0.0.0__31bf3856ad364e35/UIAutomationClientsideProviders.dll
----------------------------------------
Accessibility
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3752.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/Accessibility/v4.0_4.0.0.0__b03f5f7f11d50a3a/Accessibility.dll
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4190.0 built by: NET48REL1LAST_B
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3752.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.
```

**Comment by mdhiggins** [comment] 2020-10-10 15:43
Just pushed version 1.5, see if that fixes things
148602d8d38bff9cd078f43bd14725e7564c2204

**Comment by rodrigolopezguerra** [comment] 2020-10-13 20:11
didn't work out as expected. 

When unplug monitor

![image](https://user-images.githubusercontent.com/3514141/95910872-159fde00-0d77-11eb-81eb-a65841bfcb55.png)

All icons go to the rigth in the desktop monitor.

When plug in again monitor , they are centered

BR,

**Comment by mdhiggins** [comment] 2020-10-14 12:29
Not able to reproduce this on my dual monitor setup. Unplugging and replugging or using Win + P to toggle monitor works as expected with appropriate centering. 

Its really not anything special, all that happens is the command that the `scan for screens` command is run when this event is triggered `SystemEvents.DisplaySettingsChanging` which should capture any resolution changes or display devices being added. The fact that things work when you do it manually just means your system isn't triggering that event at the correct time. Make sure you have latest display drivers and latest version of windows

Without being able to reproduce this it's going to be very hard to fix. If you want to run the program from source and post some debug logs that's probably the only way this might get addressed but it seems to be an issue specific to your system.

Glad the crash is fixed though. Plug
